### ISSUE TITLE
crash when printing detailed results

### ISSUE THREAD

**Issue by stevvooe** [estesp/bucketbench#24]
Looks like we have an slice index when iterating over each thread:

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/estesp/bucketbench/cmd.outputRunDetails(0xa, 0xc4207801e0, 0x2, 0x2)
	/home/sjd/go/src/github.com/estesp/bucketbench/cmd/run.go:197 +0xc44
github.com/estesp/bucketbench/cmd.glob..func1(0x13e07a0, 0xc42005ec80, 0x0, 0x5, 0x0, 0x0)
	/home/sjd/go/src/github.com/estesp/bucketbench/cmd/run.go:102 +0x485
github.com/estesp/bucketbench/vendor/github.com/spf13/cobra.(*Command).execute(0x13e07a0, 0xc42005ec30, 0x5, 0x5, 0x13e07a0, 0xc42005ec30)
	/home/sjd/go/src/github.com/estesp/bucketbench/vendor/github.com/spf13/cobra/command.go:647 +0x3f8
github.com/estesp/bucketbench/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x13e0580, 0xa, 0x0, 0x0)
	/home/sjd/go/src/github.com/estesp/bucketbench/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/estesp/bucketbench/vendor/github.com/spf13/cobra.(*Command).Execute(0x13e0580, 0x0, 0x13e07a0)
	/home/sjd/go/src/github.com/estesp/bucketbench/vendor/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/sjd/go/src/github.com/estesp/bucketbench/bucketbench.go:25 +0x31
```

The command run was the following:

```
sudo PATH=$PATH `which bucketbench` run --log-level=debug -b ~/go/src/github.com/estesp/bucketbench/examples/docker.yaml
```

This was built from faea7681e5b9c96ed7a41b4bb2c77b3a5173e1b2.

**Comment by estesp** [comment]
Thanks--obviously I got addicted to `-s` to skip the Limit run, and hadn't tested that since re-organizing the detailed output :-/ Fixed in #25
